# ==============================
# Hyprpaper Default Configuration
# ==============================

# -------- Misc Options --------
# Render Hyprland splash over wallpaper
splash = false

# Vertical offset of splash text
splash_offset = 20

# Splash opacity (0.0 - 1.0)
splash_opacity = 0.8

# Enable IPC (required for hyprctl control)
ipc = true


# -------- Wallpapers --------

# Primary monitor wallpaper
wallpaper {
    monitor = DP-1
    path = ~/Images/wallpapers/arch7.png
    fit_mode = cover
}

# Secondary monitor wallpaper
wallpaper {
    monitor = HDMI-A-1
    path = ~/Images/wallpapers/arch6.jpg
    fit_mode = cover
}

# Fallback wallpaper (used if no specific monitor match)
wallpaper {
    monitor =
    path = ~/Images/wallpapers/arch4.png
    fit_mode = cover
}